/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/n3wscott/gateway/pkg/apis/gateway/v1alpha1"
	scheme "github.com/n3wscott/gateway/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GitHubsGetter has a method to return a GitHubInterface.
// A group's client should implement this interface.
type GitHubsGetter interface {
	GitHubs(namespace string) GitHubInterface
}

// GitHubInterface has methods to work with GitHub resources.
type GitHubInterface interface {
	Create(*v1alpha1.GitHub) (*v1alpha1.GitHub, error)
	Update(*v1alpha1.GitHub) (*v1alpha1.GitHub, error)
	UpdateStatus(*v1alpha1.GitHub) (*v1alpha1.GitHub, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GitHub, error)
	List(opts v1.ListOptions) (*v1alpha1.GitHubList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitHub, err error)
	GitHubExpansion
}

// gitHubs implements GitHubInterface
type gitHubs struct {
	client rest.Interface
	ns     string
}

// newGitHubs returns a GitHubs
func newGitHubs(c *GatewayV1alpha1Client, namespace string) *gitHubs {
	return &gitHubs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gitHub, and returns the corresponding gitHub object, and an error if there is any.
func (c *gitHubs) Get(name string, options v1.GetOptions) (result *v1alpha1.GitHub, err error) {
	result = &v1alpha1.GitHub{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("githubs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GitHubs that match those selectors.
func (c *gitHubs) List(opts v1.ListOptions) (result *v1alpha1.GitHubList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GitHubList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("githubs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gitHubs.
func (c *gitHubs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("githubs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a gitHub and creates it.  Returns the server's representation of the gitHub, and an error, if there is any.
func (c *gitHubs) Create(gitHub *v1alpha1.GitHub) (result *v1alpha1.GitHub, err error) {
	result = &v1alpha1.GitHub{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("githubs").
		Body(gitHub).
		Do().
		Into(result)
	return
}

// Update takes the representation of a gitHub and updates it. Returns the server's representation of the gitHub, and an error, if there is any.
func (c *gitHubs) Update(gitHub *v1alpha1.GitHub) (result *v1alpha1.GitHub, err error) {
	result = &v1alpha1.GitHub{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("githubs").
		Name(gitHub.Name).
		Body(gitHub).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *gitHubs) UpdateStatus(gitHub *v1alpha1.GitHub) (result *v1alpha1.GitHub, err error) {
	result = &v1alpha1.GitHub{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("githubs").
		Name(gitHub.Name).
		SubResource("status").
		Body(gitHub).
		Do().
		Into(result)
	return
}

// Delete takes name of the gitHub and deletes it. Returns an error if one occurs.
func (c *gitHubs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("githubs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gitHubs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("githubs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched gitHub.
func (c *gitHubs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitHub, err error) {
	result = &v1alpha1.GitHub{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("githubs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
