/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/n3wscott/gateway/pkg/apis/gateway/v1alpha1"
	scheme "github.com/n3wscott/gateway/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SlacksGetter has a method to return a SlackInterface.
// A group's client should implement this interface.
type SlacksGetter interface {
	Slacks(namespace string) SlackInterface
}

// SlackInterface has methods to work with Slack resources.
type SlackInterface interface {
	Create(*v1alpha1.Slack) (*v1alpha1.Slack, error)
	Update(*v1alpha1.Slack) (*v1alpha1.Slack, error)
	UpdateStatus(*v1alpha1.Slack) (*v1alpha1.Slack, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Slack, error)
	List(opts v1.ListOptions) (*v1alpha1.SlackList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Slack, err error)
	SlackExpansion
}

// slacks implements SlackInterface
type slacks struct {
	client rest.Interface
	ns     string
}

// newSlacks returns a Slacks
func newSlacks(c *GatewayV1alpha1Client, namespace string) *slacks {
	return &slacks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the slack, and returns the corresponding slack object, and an error if there is any.
func (c *slacks) Get(name string, options v1.GetOptions) (result *v1alpha1.Slack, err error) {
	result = &v1alpha1.Slack{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slacks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Slacks that match those selectors.
func (c *slacks) List(opts v1.ListOptions) (result *v1alpha1.SlackList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SlackList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slacks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested slacks.
func (c *slacks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("slacks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a slack and creates it.  Returns the server's representation of the slack, and an error, if there is any.
func (c *slacks) Create(slack *v1alpha1.Slack) (result *v1alpha1.Slack, err error) {
	result = &v1alpha1.Slack{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("slacks").
		Body(slack).
		Do().
		Into(result)
	return
}

// Update takes the representation of a slack and updates it. Returns the server's representation of the slack, and an error, if there is any.
func (c *slacks) Update(slack *v1alpha1.Slack) (result *v1alpha1.Slack, err error) {
	result = &v1alpha1.Slack{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("slacks").
		Name(slack.Name).
		Body(slack).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *slacks) UpdateStatus(slack *v1alpha1.Slack) (result *v1alpha1.Slack, err error) {
	result = &v1alpha1.Slack{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("slacks").
		Name(slack.Name).
		SubResource("status").
		Body(slack).
		Do().
		Into(result)
	return
}

// Delete takes name of the slack and deletes it. Returns an error if one occurs.
func (c *slacks) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slacks").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *slacks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slacks").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched slack.
func (c *slacks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Slack, err error) {
	result = &v1alpha1.Slack{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("slacks").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
