/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/n3wscott/gateway/pkg/apis/gateway/v1alpha1"
	scheme "github.com/n3wscott/gateway/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SlackbotsGetter has a method to return a SlackbotInterface.
// A group's client should implement this interface.
type SlackbotsGetter interface {
	Slackbots(namespace string) SlackbotInterface
}

// SlackbotInterface has methods to work with Slackbot resources.
type SlackbotInterface interface {
	Create(*v1alpha1.Slackbot) (*v1alpha1.Slackbot, error)
	Update(*v1alpha1.Slackbot) (*v1alpha1.Slackbot, error)
	UpdateStatus(*v1alpha1.Slackbot) (*v1alpha1.Slackbot, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Slackbot, error)
	List(opts v1.ListOptions) (*v1alpha1.SlackbotList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Slackbot, err error)
	SlackbotExpansion
}

// slackbots implements SlackbotInterface
type slackbots struct {
	client rest.Interface
	ns     string
}

// newSlackbots returns a Slackbots
func newSlackbots(c *GatewayV1alpha1Client, namespace string) *slackbots {
	return &slackbots{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the slackbot, and returns the corresponding slackbot object, and an error if there is any.
func (c *slackbots) Get(name string, options v1.GetOptions) (result *v1alpha1.Slackbot, err error) {
	result = &v1alpha1.Slackbot{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slackbots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Slackbots that match those selectors.
func (c *slackbots) List(opts v1.ListOptions) (result *v1alpha1.SlackbotList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SlackbotList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("slackbots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested slackbots.
func (c *slackbots) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("slackbots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a slackbot and creates it.  Returns the server's representation of the slackbot, and an error, if there is any.
func (c *slackbots) Create(slackbot *v1alpha1.Slackbot) (result *v1alpha1.Slackbot, err error) {
	result = &v1alpha1.Slackbot{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("slackbots").
		Body(slackbot).
		Do().
		Into(result)
	return
}

// Update takes the representation of a slackbot and updates it. Returns the server's representation of the slackbot, and an error, if there is any.
func (c *slackbots) Update(slackbot *v1alpha1.Slackbot) (result *v1alpha1.Slackbot, err error) {
	result = &v1alpha1.Slackbot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("slackbots").
		Name(slackbot.Name).
		Body(slackbot).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *slackbots) UpdateStatus(slackbot *v1alpha1.Slackbot) (result *v1alpha1.Slackbot, err error) {
	result = &v1alpha1.Slackbot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("slackbots").
		Name(slackbot.Name).
		SubResource("status").
		Body(slackbot).
		Do().
		Into(result)
	return
}

// Delete takes name of the slackbot and deletes it. Returns an error if one occurs.
func (c *slackbots) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slackbots").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *slackbots) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("slackbots").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched slackbot.
func (c *slackbots) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Slackbot, err error) {
	result = &v1alpha1.Slackbot{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("slackbots").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
