/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	gatewayv1alpha1 "github.com/n3wscott/gateway/pkg/apis/gateway/v1alpha1"
	versioned "github.com/n3wscott/gateway/pkg/client/clientset/versioned"
	internalinterfaces "github.com/n3wscott/gateway/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/n3wscott/gateway/pkg/client/listers/gateway/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SlackbotInformer provides access to a shared informer and lister for
// Slackbots.
type SlackbotInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SlackbotLister
}

type slackbotInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSlackbotInformer constructs a new informer for Slackbot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSlackbotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSlackbotInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSlackbotInformer constructs a new informer for Slackbot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSlackbotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GatewayV1alpha1().Slackbots(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GatewayV1alpha1().Slackbots(namespace).Watch(options)
			},
		},
		&gatewayv1alpha1.Slackbot{},
		resyncPeriod,
		indexers,
	)
}

func (f *slackbotInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSlackbotInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *slackbotInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&gatewayv1alpha1.Slackbot{}, f.defaultInformer)
}

func (f *slackbotInformer) Lister() v1alpha1.SlackbotLister {
	return v1alpha1.NewSlackbotLister(f.Informer().GetIndexer())
}
