/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/n3wscott/gateway/pkg/apis/gateway/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSlacks implements SlackInterface
type FakeSlacks struct {
	Fake *FakeGatewayV1alpha1
	ns   string
}

var slacksResource = schema.GroupVersionResource{Group: "gateway.n3wscott.com", Version: "v1alpha1", Resource: "slacks"}

var slacksKind = schema.GroupVersionKind{Group: "gateway.n3wscott.com", Version: "v1alpha1", Kind: "Slack"}

// Get takes name of the slack, and returns the corresponding slack object, and an error if there is any.
func (c *FakeSlacks) Get(name string, options v1.GetOptions) (result *v1alpha1.Slack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(slacksResource, c.ns, name), &v1alpha1.Slack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Slack), err
}

// List takes label and field selectors, and returns the list of Slacks that match those selectors.
func (c *FakeSlacks) List(opts v1.ListOptions) (result *v1alpha1.SlackList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(slacksResource, slacksKind, c.ns, opts), &v1alpha1.SlackList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SlackList{ListMeta: obj.(*v1alpha1.SlackList).ListMeta}
	for _, item := range obj.(*v1alpha1.SlackList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested slacks.
func (c *FakeSlacks) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(slacksResource, c.ns, opts))

}

// Create takes the representation of a slack and creates it.  Returns the server's representation of the slack, and an error, if there is any.
func (c *FakeSlacks) Create(slack *v1alpha1.Slack) (result *v1alpha1.Slack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(slacksResource, c.ns, slack), &v1alpha1.Slack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Slack), err
}

// Update takes the representation of a slack and updates it. Returns the server's representation of the slack, and an error, if there is any.
func (c *FakeSlacks) Update(slack *v1alpha1.Slack) (result *v1alpha1.Slack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(slacksResource, c.ns, slack), &v1alpha1.Slack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Slack), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSlacks) UpdateStatus(slack *v1alpha1.Slack) (*v1alpha1.Slack, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(slacksResource, "status", c.ns, slack), &v1alpha1.Slack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Slack), err
}

// Delete takes name of the slack and deletes it. Returns an error if one occurs.
func (c *FakeSlacks) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(slacksResource, c.ns, name), &v1alpha1.Slack{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSlacks) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(slacksResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SlackList{})
	return err
}

// Patch applies the patch and returns the patched slack.
func (c *FakeSlacks) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Slack, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(slacksResource, c.ns, name, pt, data, subresources...), &v1alpha1.Slack{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Slack), err
}
