/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/n3wscott/gateway/pkg/apis/gateway/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSlackbots implements SlackbotInterface
type FakeSlackbots struct {
	Fake *FakeGatewayV1alpha1
	ns   string
}

var slackbotsResource = schema.GroupVersionResource{Group: "gateway.n3wscott.com", Version: "v1alpha1", Resource: "slackbots"}

var slackbotsKind = schema.GroupVersionKind{Group: "gateway.n3wscott.com", Version: "v1alpha1", Kind: "Slackbot"}

// Get takes name of the slackbot, and returns the corresponding slackbot object, and an error if there is any.
func (c *FakeSlackbots) Get(name string, options v1.GetOptions) (result *v1alpha1.Slackbot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(slackbotsResource, c.ns, name), &v1alpha1.Slackbot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Slackbot), err
}

// List takes label and field selectors, and returns the list of Slackbots that match those selectors.
func (c *FakeSlackbots) List(opts v1.ListOptions) (result *v1alpha1.SlackbotList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(slackbotsResource, slackbotsKind, c.ns, opts), &v1alpha1.SlackbotList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SlackbotList{ListMeta: obj.(*v1alpha1.SlackbotList).ListMeta}
	for _, item := range obj.(*v1alpha1.SlackbotList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested slackbots.
func (c *FakeSlackbots) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(slackbotsResource, c.ns, opts))

}

// Create takes the representation of a slackbot and creates it.  Returns the server's representation of the slackbot, and an error, if there is any.
func (c *FakeSlackbots) Create(slackbot *v1alpha1.Slackbot) (result *v1alpha1.Slackbot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(slackbotsResource, c.ns, slackbot), &v1alpha1.Slackbot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Slackbot), err
}

// Update takes the representation of a slackbot and updates it. Returns the server's representation of the slackbot, and an error, if there is any.
func (c *FakeSlackbots) Update(slackbot *v1alpha1.Slackbot) (result *v1alpha1.Slackbot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(slackbotsResource, c.ns, slackbot), &v1alpha1.Slackbot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Slackbot), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSlackbots) UpdateStatus(slackbot *v1alpha1.Slackbot) (*v1alpha1.Slackbot, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(slackbotsResource, "status", c.ns, slackbot), &v1alpha1.Slackbot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Slackbot), err
}

// Delete takes name of the slackbot and deletes it. Returns an error if one occurs.
func (c *FakeSlackbots) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(slackbotsResource, c.ns, name), &v1alpha1.Slackbot{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSlackbots) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(slackbotsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SlackbotList{})
	return err
}

// Patch applies the patch and returns the patched slackbot.
func (c *FakeSlackbots) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Slackbot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(slackbotsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Slackbot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Slackbot), err
}
